language: node_js
node_js:
  - 8


script:
  - CI=true npm run build

deploy:
  provider: script
  script: "npm run deploy"
  skip_cleanup: true

before_deploy:
- git remote set-url origin https://${GH_TOKEEN}@github.com/howech/caravan.git
- git config --global user.email "Travis<chris+travis@howeville.com>"
- git config --global user.name "howech (via travis)"

